[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
included-patches = "disable-shorts-on-startup hide-ads old-video-quality-menu open-links-externally remember-video-quality video-ads"
exclusive-patches = true
