enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
included-patches = "'Restore old video quality menu' 'Remember video quality' 'Remove tracking query parameter' 'Open links externally' 'Disable suggested video end screen' 'Disable resuming Shorts on startup' 'Video ads' 'Hide ads'"
exclusive-patches = true

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
included-patches = "'Open links with app chooser'"
excluded-patches = "'Dynamic color'"

