enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
included-patches = "'Hide ads' 'Sanitize sharing links'"
exclusive-patches = true

