enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
excluded-patches = "'Dynamic color'"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
excluded-patches = "'Unlock premium Reddit icons'"
