enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube Revanced]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'GmsCore support' 'Remove tracking query parameter' 'Bypass URL redirects' 'Open links externally' 'Hide ads' 'Video ads' 'Hide floating microphone button' 'Restore old video quality menu' 'Remember video quality' 'Copy video URL'"
exclusive-patches = true
